name: Deploy Nuxt

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Generate static site (SSG)
        env:
          NUXT_PUBLIC_SITE_URL: ${{ secrets.NUXT_PUBLIC_SITE_URL }}
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION: ${{ secrets.NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION }}
        run: npm run generate

      - name: Archive dist folder
        run: tar -czf dist.tar.gz dist/

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'dist.tar.gz'
          target: '/home/developer/'

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/furitech/frontend/releases
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            mkdir $TIMESTAMP
            tar -xzf /home/developer/dist.tar.gz -C $TIMESTAMP

            mv $TIMESTAMP/dist/* $TIMESTAMP/
            rm -rf $TIMESTAMP/dist

            sudo ln -sfn /var/www/furitech/frontend/releases/$TIMESTAMP /var/www/furitech/frontend/current

            ls -dt /var/www/furitech/frontend/releases/* 2>/dev/null | tail -n +6 | xargs -r rm -rf
